#auth.py
import jwt
from config import settings

#! here the code is generated by ai
#! verify if it works because auth depends on it
def get_current_user(authorization: str = Header(...)):
    if not authorization.startswith("Bearer "):
        raise HTTPException(status_code=401, detail="Missing or invalid token header")
    
    token = authorization.split(" ")[1]
    
    try:
        # Decodes token locally using Clerk's public key
        payload = jwt.decode(
            token, 
            settings.CLERK_PUBLIC_KEY, 
            algorithms=["RS256"], 
            options={"verify_aud": False}
        )
        return payload  # Contains 'sub' (Clerk User ID) and 'email'
    except jwt.PyJWTError:
        raise HTTPException(status_code=401, detail="Invalid or expired token")